# Generated by Django 3.2 on 2021-06-27 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(default=my_app.models.generate_shift_id, max_length=10, unique=True)),
                ('area', models.CharField(default=my_app.models.generate_shift_id, max_length=10)),
                ('booked', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('modified_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('CANCELLED', 'CANCELLED')], max_length=20, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
