# Generated by Django 3.2 on 2021-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_shiftdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='mobile_number',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
    ]
